###############
## 
####
# 0 2|5 6
GPU: [0]

VERBOSE: True

MODEL:
  SESSION: 'model_C'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 32
  NUM_EPOCHS: 100
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 256
  VAL_PS: 256
  TRAIN_DIR: '../../../share/UIE/datasets/train_C' # path to training data
  VAL_DIR: '../../../share/UIE/datasets/val_C'    # path to validation data
  SAVE_DIR: './checkpoints'     # path to save models and images
  # SAVE_IMAGES: False
